[firebase]
private_key_id = "42721e88bce66ca02734520ae2903c3d9faf2362"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCaqKQydl/HUhDJ
ITaxou82BVWbx1WNWeinv5jZNEjmsVmwxdKlsjCsZsTTdiDr2sfUUHl3sI9CKq3F
4fatSTIx74+GspGhYzdkHk5r9zpuY5ZoY9fK/KMZeB1dwtcsX1hNcsOy743bhNm6
2rVWsh6nmhRZmfHrOKjfWbqUc+WJvsp/hd+uP5GERsezNb+Vq+ppzkbs2Yk8oRGc
0FZRa8Ejnl/lcyw/r9c54DOhbSCZGU2D2S5u+s1nBPDF0Y3mqX4EAtJ39QIC/99Y
WXSJCvbX8AdCSuVR+8vHONkYVykavgjqj9qGKpSV8i2JHjevaLcFwJC5FcllCOcp
ZoiIXTx9AgMBAAECggEAAx2B6GXonWMcGHKoheDianDZqrO6Su8ayx1syEJ2QRAl
RNsvPr9j0Jn/Vynj4hK7/+nt3Tw7hOZg+rS7AcsqjV8mDnbUjSIqlvcvUDU6KMgT
wWvyO4Uyo3KY1zvzlp65cIUiLdDUFC4AYfQO2NccqMNnRO8sNGpydSrhbot8StwU
PGebjPZv1EVTFbSVI20611NIiBhcpDZcjuXHl5Oymu1Cut1LG3iPwyzmj1npbaR0
gVtq86w8G9rH6RS0GJHdoVeM8PPIR0+hbr+dh0m4Z+9skZCu9G0Xetf+u3FQqi+6
klVVwOnQ9ll5nvi8FnoCG3tr40wTWf/qKPqMUs5lIQKBgQDYnBllcwg0m/W4Ck7C
N9OhB29f3S+2VYma0SW1hx8VKL8dhydoBrL8CSid4JLq1p0MjqJFmygAN9fb0J5K
8ORLSYRXro0o32r4w9Fa7ApoIzJ1a5o+rLr0dUXOZO6tCFMP7+wWHYLdUdle698X
487uJmRybjnAVcK4jFPyjx8yTQKBgQC2yISXSXjfTQzT4ulY28Qu00TY8phm/RUG
vAJreCesp2ndmabbwKnZl8uXVV2KLxsWlTyW+UDlaFPkmbQv6/wKQUGNP3FsDsCa
VUOcPYYJeA492hfQpdN3Zei6y+k61ds+ZF2+WVdH1/AWr983h42l6OU1oykXdCQU
GveIbVdq8QKBgErhq+XmXm/ReqCk75U0t3RznY0GafgemfNrWh3nGFe4Pll236iW
qEl44RGzERceGiy9Ilvtx2ZL59OVyyMdI87jG100epgmpFRbXYSRFQfrIwZ0rF3+
WKMp53fybJBk0FIyHuuGSDc6lGq8H+OiXWb23sKwWEalXyttV5gC4kYBAoGBAKPm
He7CtR4Wqx/8Yp2JQttyGlQnBL2kxovpXoobjgflfqp0swhuNF+nG6oxo9Ta9IFF
hLUkACs1Z7SeltI52yEe7rbHYt8wQ0igmCWrjVtEShDwVVaEu6Bew1dsrVBSn2vM
97pNxlPnr6PIRHI4nK1ertlv2tLrE8brf3bYBQEhAoGAEkaDEPwaZWgI0dTs+uEF
BI3O/dnSMGU3ZBZWP2uMgyaF4n2inkSs1u/8A1mYBnfKbwA0jh85O2nuykyrENMA
yToi+QO49reF+9vmSmVzBNY/Z6MUFqNdDCoZ2CJoQ4yR0Lq2JwMNU1m8zb+dPQIX
nfhKhPeHwqaX2j8T8USod7A=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-1aurm@sirisampadaclinic.iam.gserviceaccount.com"
client_id = "103988370674664331708"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-1aurm%40sirisampadaclinic.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


